function [] = CheckViral( data )
    Viral = (1/(data.Number.Na + data.Number.Rb))* ...
        (( 2*data.Outputs.Dispersion_energy{1}(end) - ...
           2*data.Outputs.Potential_energy{1}(end)+ ...
           3*data.Outputs.Nonlinear_energy{1}(end) ...
        ) * data.Number.Na + ...
        ( 2*data.Outputs.Dispersion_energy{2}(end) - ...
          2*data.Outputs.Potential_energy{2}(end)+...
          3*data.Outputs.Nonlinear_energy{2}(end) ...
        ) * data.Number.Rb);
    fprintf('%f',Viral);
end