function [] = PrintTotalEnergy( data )
    Energy = (1/(data.Number.Na + data.Number.Rb))* ...
        (( data.Outputs.Dispersion_energy{1}(end) + ...
           data.Outputs.Nonlinear_energy{1}(end) + ...
           data.Outputs.Potential_energy{1}(end) ...
        ) * data.Number.Na + ...
        ( data.Outputs.Dispersion_energy{2}(end) + ...
           data.Outputs.Nonlinear_energy{2}(end) + ...
           data.Outputs.Potential_energy{2}(end) ...
        ) * data.Number.Rb);
    fprintf('%f',Energy);
end